query collectionDetail($address: ID!) {
  collection(id: $address) {
    ... CollectionInfo
    recentlyActiveNfts: nftOwners(
      orderBy: lastActivityAtTimestamp
      orderDirection: desc
      first: 50)
    {
      id
      nft { ... NFTInfo }
      owner { id address }
      balance
      createdAtTimestamp
      lastActivityAtTimestamp
    }
  }
}
