query getNfts(
  $orderBy: NFT_orderBy = tokenId
  $orderDirection: OrderDirection = asc
  $filter: NFT_filter
) {
  nfts(
    orderBy: $orderBy
    orderDirection: $orderDirection
    where: $filter
    first: 100
  ) {
    id
    tokenId
  }
}

query getNftOwners(
  $orderBy: NFTOwner_orderBy = lastActivityAtTimestamp
  $orderDirection: OrderDirection = desc
  $filter: NFTOwner_filter
) {
  nftowners(
    orderBy: $orderBy
    orderDirection: $orderDirection
    where: $filter
    first: 100
  ) {
    id
    nft { id tokenId }
  }
}

query getTokenStorage(
  $orderBy: TokenStorageValue_orderBy
  $orderDirection: OrderDirection = asc
  $filter: TokenStorageValue_filter
  $limit: Int! = 100
) {
  tokenStorageValues(
    orderBy: $orderBy
    orderDirection: $orderDirection
    where: $filter
    first: $limit
  ) {
    id
    nft { id tokenId }
    key
    stringValue
    intValue
  }
}
